---
target_dir: 'backup_destination_without_trailing_slash'
latest: 'latest'
src:
  - '/'
exclude:
  - '*'
date_format: '%Y-%m-%d_%H-%M-%S'
full:
  cycle:
    days: 90
    hours: 0
    minutes: 0
    seconds: 0
intervals:
  - name: hourly
    prio: 4
    num: 20
    cycle:
      days: 0
      hours: 1
      minutes: 0
      seconds: 0
  - name: daily
    prio: 3
    num: 14
    cycle:
      days: 1
      hours: 0
      minutes: 0
      seconds: 0
  - name: weekly
    prio: 2
    num: 4
    cycle:
      days: 7
      hours: 0
      minutes: 0
      seconds: 0
  - name: monthly
    prio: 1
    num: 12
    cycle:
      days: 30
      hours: 0
      minutes: 0
      seconds: 0
  - name: yearly
    prio: 0
    num: 5
    cycle:
      days: 365
      hours: 0
      minutes: 0
      seconds: 0

